version: '3'

services:
  db:
    image: postgres:10.14    
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
      - ${DATABASE_LOG_DIR}:/var/log/postgresql
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
 
  pgadmin:
    image: 'dpage/pgadmin4'    
    volumes:
      - '${PGADMIN_DATA}:/var/lib/pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    links:
      - db:pgsql-server